// Code generated by protoc-gen-go.
// source: raft.proto
// DO NOT EDIT!

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	PostArgs
	PostResponse
	LookupArgs
	LookupResponse
	RequestVoteArgs
	RequestVoteResponse
	AppendEntriesArgs
	AppendEntriesResponse
	LogEntry
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type PostArgs struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *PostArgs) Reset()                    { *m = PostArgs{} }
func (m *PostArgs) String() string            { return proto.CompactTextString(m) }
func (*PostArgs) ProtoMessage()               {}
func (*PostArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PostResponse struct {
	Resp string `protobuf:"bytes,1,opt,name=resp" json:"resp,omitempty"`
}

func (m *PostResponse) Reset()                    { *m = PostResponse{} }
func (m *PostResponse) String() string            { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()               {}
func (*PostResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LookupArgs struct {
}

func (m *LookupArgs) Reset()                    { *m = LookupArgs{} }
func (m *LookupArgs) String() string            { return proto.CompactTextString(m) }
func (*LookupArgs) ProtoMessage()               {}
func (*LookupArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LookupResponse struct {
	Messages []string `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *LookupResponse) Reset()                    { *m = LookupResponse{} }
func (m *LookupResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()               {}
func (*LookupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RequestVoteArgs struct {
	// candidate’s term
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// candidate requesting vote
	CandidateId uint32 `protobuf:"varint,2,opt,name=candidateId" json:"candidateId,omitempty"`
	// index of candidate’s last log entry
	LastLogIndex uint32 `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	// term of candidate’s last log entry
	LastLogTerm uint32 `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *RequestVoteArgs) Reset()                    { *m = RequestVoteArgs{} }
func (m *RequestVoteArgs) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteArgs) ProtoMessage()               {}
func (*RequestVoteArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RequestVoteResponse struct {
	// currentTerm, for candidate to update itself
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// true means candidate received vote
	VoteGranted bool `protobuf:"varint,2,opt,name=voteGranted" json:"voteGranted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AppendEntriesArgs struct {
	// leader’s term
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// so follower can redirect clients
	LeaderId uint32 `protobuf:"varint,2,opt,name=leaderId" json:"leaderId,omitempty"`
	// index of log entry immediately preceding new ones
	PrevLogIndex uint32 `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	// term of prevLogIndex entry
	PrevLogTerm uint32 `protobuf:"varint,4,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	// log entries to store (empty for heartbeat; may send more than one for efficiency)
	Entries []*LogEntry `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	// leader’s commitIndex
	LeaderCommit uint32 `protobuf:"varint,6,opt,name=leaderCommit" json:"leaderCommit,omitempty"`
}

func (m *AppendEntriesArgs) Reset()                    { *m = AppendEntriesArgs{} }
func (m *AppendEntriesArgs) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesArgs) ProtoMessage()               {}
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AppendEntriesArgs) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	// currentTerm, for leader to update itself
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// true if follower contained entry matching prevLogIndex and prevLogTerm
	Success bool `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type LogEntry struct {
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*PostArgs)(nil), "raft.PostArgs")
	proto.RegisterType((*PostResponse)(nil), "raft.PostResponse")
	proto.RegisterType((*LookupArgs)(nil), "raft.LookupArgs")
	proto.RegisterType((*LookupResponse)(nil), "raft.LookupResponse")
	proto.RegisterType((*RequestVoteArgs)(nil), "raft.RequestVoteArgs")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*AppendEntriesArgs)(nil), "raft.AppendEntriesArgs")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Raft service

type RaftClient interface {
	Post(ctx context.Context, in *PostArgs, opts ...grpc.CallOption) (*PostResponse, error)
	Lookup(ctx context.Context, in *LookupArgs, opts ...grpc.CallOption) (*LookupResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) Post(ctx context.Context, in *PostArgs, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/Post", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) Lookup(ctx context.Context, in *LookupArgs, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	Post(context.Context, *PostArgs) (*PostResponse, error)
	Lookup(context.Context, *LookupArgs) (*LookupResponse, error)
	RequestVote(context.Context, *RequestVoteArgs) (*RequestVoteResponse, error)
	AppendEntries(context.Context, *AppendEntriesArgs) (*AppendEntriesResponse, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Post(ctx, req.(*PostArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Lookup(ctx, req.(*LookupArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _Raft_Post_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Raft_Lookup_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x53, 0x5b, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0xda, 0xd0, 0x86, 0xdb, 0x07, 0xc5, 0x50, 0x11, 0x02, 0x1f, 0x95, 0xbf, 0x2a, 0x84,
	0xaa, 0xaa, 0x2c, 0x00, 0x55, 0xa8, 0x42, 0x15, 0xfd, 0x40, 0x11, 0xe2, 0x3f, 0x34, 0x97, 0xa8,
	0xa2, 0x89, 0x83, 0xed, 0x56, 0xb0, 0x88, 0x59, 0xdf, 0x6c, 0x62, 0x16, 0x31, 0xb6, 0x93, 0x78,
	0xdc, 0xc7, 0xcc, 0x9f, 0xef, 0xb9, 0xaf, 0x73, 0x6e, 0x4e, 0x00, 0x78, 0xf2, 0x5b, 0xce, 0x4a,
	0xce, 0x24, 0x23, 0xbe, 0x7e, 0xd3, 0xf7, 0x10, 0x7c, 0x67, 0x42, 0x2e, 0x79, 0x26, 0xc8, 0x08,
	0xda, 0xb9, 0xc8, 0x42, 0x6f, 0xe2, 0x4d, 0x9f, 0xc7, 0xfa, 0x49, 0x29, 0xf4, 0x75, 0x36, 0x46,
	0x51, 0xb2, 0x42, 0x20, 0x21, 0xe0, 0x73, 0xf5, 0xae, 0x4b, 0xcc, 0x9b, 0xf6, 0x01, 0x36, 0x8c,
	0xfd, 0x39, 0x94, 0x7a, 0x06, 0xfd, 0x08, 0xc3, 0x2a, 0xb2, 0x3d, 0x11, 0x04, 0x39, 0x0a, 0x91,
	0x64, 0x28, 0x54, 0x5f, 0x5b, 0xf5, 0xd9, 0x98, 0xde, 0x78, 0xf0, 0x22, 0xc6, 0xbf, 0x07, 0x14,
	0xf2, 0x27, 0x93, 0x68, 0x58, 0xa8, 0x1d, 0x12, 0x79, 0x6e, 0x76, 0x0c, 0x62, 0xf3, 0x26, 0x13,
	0xe8, 0x6d, 0x93, 0x22, 0xdd, 0xa5, 0x89, 0xc4, 0x75, 0x1a, 0xb6, 0x4c, 0xca, 0x85, 0x88, 0x62,
	0xba, 0x4f, 0x84, 0xdc, 0xb0, 0x6c, 0x5d, 0xa4, 0xf8, 0x2f, 0x6c, 0x9b, 0x92, 0x13, 0x4c, 0x4f,
	0xa9, 0xe3, 0x1f, 0x7a, 0x81, 0x5f, 0x4d, 0x71, 0x20, 0xfa, 0x0d, 0x5e, 0x39, 0x74, 0x5c, 0xd9,
	0xd7, 0x28, 0x1d, 0x55, 0xcd, 0x57, 0x9e, 0x14, 0x12, 0x2b, 0x4a, 0x41, 0xec, 0x42, 0xf4, 0xd6,
	0x83, 0x97, 0xcb, 0xb2, 0xc4, 0x22, 0x5d, 0x15, 0x92, 0xef, 0x50, 0x3c, 0x2a, 0x4f, 0x9d, 0x68,
	0x8f, 0x49, 0x8a, 0xdc, 0x6a, 0xb3, 0xb1, 0x16, 0x56, 0x72, 0x3c, 0x9e, 0x0b, 0x73, 0x31, 0xcd,
	0xa5, 0x8e, 0x5d, 0x61, 0x0e, 0x44, 0xa6, 0xd0, 0xc5, 0x8a, 0x44, 0xf8, 0x4c, 0x7d, 0x83, 0xde,
	0x62, 0x38, 0x33, 0x56, 0x50, 0x79, 0x4d, 0xee, 0x7f, 0xdc, 0xa4, 0xcd, 0x21, 0xcd, 0xee, 0x2f,
	0x2c, 0xcf, 0x77, 0x32, 0xec, 0xd4, 0x87, 0x74, 0x30, 0xba, 0x82, 0xf1, 0x89, 0xb0, 0x27, 0x0f,
	0x15, 0x42, 0x57, 0x1c, 0xb6, 0x5b, 0xf5, 0xc9, 0xeb, 0x23, 0x35, 0x21, 0x9d, 0x43, 0xd0, 0xec,
	0xbf, 0xda, 0x59, 0xfb, 0xb1, 0x65, 0xfd, 0xb8, 0xb8, 0xf3, 0xc0, 0x8f, 0x15, 0x6f, 0xf2, 0x01,
	0x7c, 0x6d, 0x4c, 0x52, 0xcb, 0x68, 0x2c, 0x1c, 0x91, 0x87, 0xd8, 0x92, 0x9a, 0x43, 0xa7, 0xb2,
	0x24, 0x19, 0x35, 0xa2, 0x1b, 0xbb, 0x46, 0xaf, 0x5d, 0xc4, 0x76, 0x7c, 0x86, 0x9e, 0x63, 0x03,
	0x32, 0xae, 0x8a, 0xce, 0x8c, 0x1a, 0xbd, 0xbd, 0x80, 0xed, 0x80, 0x15, 0x0c, 0x4e, 0x0e, 0x44,
	0xde, 0x54, 0xb5, 0x17, 0x76, 0x88, 0xde, 0x5d, 0x49, 0x34, 0x63, 0x7e, 0x75, 0xcc, 0x9f, 0xfa,
	0xe9, 0x3e, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x1b, 0x36, 0x6e, 0xb7, 0x03, 0x00, 0x00,
}
